export const ADD_ADDRESS_BOOK = 'ADD_ADDRESS_BOOK';
export const ADD_ADDRESS_BOOK_START = 'ADD_ADDRESS_BOOK_START';
export const ADD_ADDRESS_BOOK_ERROR = 'ADD_ADDRESS_BOOK_ERROR';

export const UPDATE_ADDRESS_BOOK = 'UPDATE_ADDRESS_BOOK';
export const UPDATE_ADDRESS_BOOK_START = 'UPDATE_ADDRESS_BOOK_START';
export const UPDATE_ADDRESS_BOOK_ERROR = 'UPDATE_ADDRESS_BOOK_ERROR';

export const GET_ADDRESS_BOOK = 'GET_ADDRESS_BOOK';
export const GET_ADDRESS_BOOK_START = 'GET_ADDRESS_BOOK_START';
export const GET_ADDRESS_BOOK_ERROR = 'GET_ADDRESS_BOOK_ERROR';

export const CLEAR_ERROR_ADDRESS_BOOK = 'CLEAR_ERROR_ADDRESS_BOOK';
export const GET_ADDRESS_BOOK_LIST_PAGEABLE = 'GET_ADDRESS_BOOK_LIST_PAGEABLE';

export const GET_ADDRESS_BOOK_LIST = 'GET_ADDRESS_BOOK_LIST';
export const GET_ADDRESS_BOOK_LIST_START = 'GET_ADDRESS_BOOK_LIST_START';
export const GET_ADDRESS_BOOK_LIST_ERROR = 'GET_ADDRESS_BOOK_LIST_ERROR';

export const DELETE_ADDRESS_BOOK = 'DELETE_ADDRESS_BOOK';
export const DELETE_ADDRESS_BOOK_START = 'DELETE_ADDRESS_BOOK_START';
export const DELETE_ADDRESS_BOOK_ERROR = 'DELETE_ADDRESS_BOOK_ERROR';

export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';